services:
  # web:
  #   container_name: odoo
  #   image: odoo:17.0
  #   depends_on:
  #     - db
  #   ports:
  #     - "8069:8069"
  #   volumes:
  #     - ./odoo-extra-addons:/mnt/extra-addons
  #     - ./odoo-conf:/etc/odoo
  #   environment:
  #     - HOST=db
  #     - USER=odoo
  #     - PASSWORD=odoo
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=odoo
  #     - POSTGRES_PASSWORD=odoo
  #   networks:
  #     - odoo-net
  #   restart: always
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5433:5432"
    networks:
      - odoo-net
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@odoo.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    networks:
      - odoo-net
    restart: always
networks:
  odoo-net:
    driver: bridge