services:
  web:
    container_name: odoo
    image: odoo:9.0
    depends_on:
      - db_9
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ./odoo-conf:/etc/odoo
      # - ./odoo-data:/var/lib/odoo
    environment:
      - HOST=db_9
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
      - odoo9-net
    restart: always
  db_9:
    container_name: db_9
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5433:5432"
    networks:
      - odoo9-net
    restart: always
networks:
  odoo9-net:
    driver: bridge
